default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgres://postgres@db/advanon_dev

test:
  <<: *default
  url: postgres://postgres@db/advanon_test

